spring:
  application:
    name: susu-dividend

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    database: h2

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dividend;DB_CLOSE_DELAY=-1
    username: sa
    password:

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6378

  jwt:
    secret: c3ViaW4tc3ByaW5nLWJvb3QtZGl2aWRlbmQtcHJvamVjdC10dXRvcmlhbC1qd3Qtc2VjcmV0LWtleQo=

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"
